name: CI and Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest test_app.py

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Verify Docker version
      run: docker --version   # This will print Docker version to the logs

    - name: Build Docker image
      run: |
        export DOCKER_BUILDKIT=0  # Disable buildx (optional)
        docker build -t ${{ secrets.DOCKER_USERNAME }}/python-hello-world .  # Add `.` as the build context

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/python-hello-world
